### ISSUE TITLE
Getting Current user in all states

### ISSUE THREAD

**Issue by ashoktamang** [subhay389/SplitShop#4]
For now, getting current user requires logging everytime. This solution is cumbersome and requires a lot of time.

**Comment by aaronksaunders** [comment]
this was reviewed in class and given as assigned reading, I know what information I have provided the class, failure to utilize the resources made available is not an excuse for not completing the assignment 
- https://github.com/aaronksaunders/hu1/wiki/4.3-An-Approach-to-Authentication-Flow-with-UI-Router

**Comment by ashoktamang** [comment]
@aaronksaunders  resolved.
