### ISSUE TITLE
Stripe Payment Sandbox needs SSL certificate?

### ISSUE THREAD

**Issue by ashoktamang** [subhay389/SplitShop#8]
https://www.airpair.com/javascript/integrating-stripe-into-angular-app

This article says that integration of stripe requires installs SSL certificate beforehand for security reasons.

Please guide me to correct links if this I am looking at wrong article.

**Comment by aaronksaunders** [comment]
i integrated this plugin in less than an hour.... no need for https server for payments...

https://github.com/Telerik-Verified-Plugins/Stripe

**Comment by ashoktamang** [comment]
I am getting this error while tyring to add the plugin:

<img width="1221" alt="screen shot 2015-12-03 at 5 14 38 am" src="https://cloud.githubusercontent.com/assets/8727746/11557822/dc17f83e-997c-11e5-9143-302074460a03.png">

I used live secret key for this instance, I also tried test secret key and publish key, which returned the same error.

**Comment by SalmonRanjay** [comment]
try removing the quotes => " " around your api key

**Comment by shitoshp** [comment]
when i tried in my windows device, it gave me an error "cross device link not permitted". i found online suggestions to reinstall cordova so i tried doing so and it still didn't work

**Comment by ashoktamang** [comment]
<img width="1141" alt="screen shot 2015-12-03 at 2 07 08 pm" src="https://cloud.githubusercontent.com/assets/8727746/11570801/2da38142-99c7-11e5-8f29-ea5d52295a95.png">

<img width="1106" alt="screen shot 2015-12-03 at 2 12 27 pm" src="https://cloud.githubusercontent.com/assets/8727746/11570962/00ca2c56-99c8-11e5-84ad-14d07061a06d.png">

same error. I had tried these approaches as well before opening up the issue again.

**Comment by SalmonRanjay** [comment]
![screen shot 2015-12-03 at 2 42 25 pm](https://cloud.githubusercontent.com/assets/3756977/11571829/4e5a712a-99cc-11e5-9c3e-cbc6ca6be81f.png)
I just ran the same command

**Comment by ashoktamang** [comment]
do you know the reason why its not running on my machine?

**Comment by ashoktamang** [comment]
Okay, its resolved now. There was an extra space. Thanks @SalmonRanjay
