### ISSUE TITLE
How to integrate semantics3 api in the app? 

### ISSUE THREAD

**Issue by ashoktamang** [subhay389/SplitShop#9]
I was able to run semantics3 api in the terminal via curl command:

curl -G -H "api_key: YOUR_API_KEY" https://api.semantics3.com/test/v1/products --data-urlencode 'q={"search":"apple iphone"}'

But when I tried to integrate the api in the project, I got the following error:
https://api.semantics3.com/test/v1/products?q={%27search%27:%20%27apple%20iphone%27}

For testing, I put the logic in the dashboard state. This is the snippet of the file:

<img width="789" alt="screen shot 2015-12-02 at 8 45 42 pm" src="https://cloud.githubusercontent.com/assets/8727746/11549694/48b50528-9936-11e5-8aaa-92cf498c2ebe.png">

**Comment by aaronksaunders** [comment]
you need to set the API key in the header... look through the parse documentation in headers @ashoktamang

**Comment by ashoktamang** [comment]
I tried putting API key in the header like the following:
<img width="998" alt="screen shot 2015-12-03 at 5 18 21 am" src="https://cloud.githubusercontent.com/assets/8727746/11557884/4fe363b6-997d-11e5-8736-4a486d49edc0.png">

But it throws the same error as before:
https://api.semantics3.com/test/v1/products?q=%7B%27search%27:%20%27apple%20iphone%27%7D

I also researched into the issue and found this stackoverflow discussion:
http://stackoverflow.com/questions/21562550/semantics3-api-with-angularjs-authentication

<img width="777" alt="screen shot 2015-12-03 at 5 19 54 am" src="https://cloud.githubusercontent.com/assets/8727746/11557924/83ed0946-997d-11e5-8f97-d48f2504c7f1.png">

So, I tried to follow this github solution for integration node server:
https://github.com/Semantics3/semantics3-node

The example code in the nodeJS files do work after I passed the api_key.

I do not understand properly what is happening here.

**Comment by ashoktamang** [comment]
@SalmonRanjay will you look into this issue as well?

**Comment by aaronksaunders** [comment]
PLEASE stop pasting screenshots.... insert the actual code or the file where the code is @ashoktamang

**Comment by aaronksaunders** [comment]
this code works fine on device or emulator, if you want to run in browser then you need a cors plugin for chrome.

This is the test API but it should be fine, BTW your code looks unnacceptable, it is not formatted and it is difficult to read

``` Javascript
  var url = "https://api.semantics3.com/test/v1/products?q=";
  var queryString = '{"cat_id":13658,"brand":"Toshiba","model":"Satellite"}';
  var options = {
    headers: {
      api_key: "SEM34407FB98C95C3B354DE771C3C05EF273"
    }
  };
  $http.get(url + queryString, options);
})
```
